### ISSUE TITLE
Running problems

### ISSUE THREAD

**Issue by yebuxiu123** [bgpantojar/LOD3_buildings#1]
Hello author, I have read your project carefully and am very interested in it. But I met some problems when I reproduced it. All my steps followed your instructions，when I run 

./LOD3.sh ../examples/p2_LOD3_00_School_main_op.py ../examples/p2_LOD3_00_School_main_LOD3.py

The following problems arise,I don't know why these errors occur, and they don't seem to affect the end result of the code, but I don't know if they are normal. I hope you can answer my question. Thank you

./LOD3.sh: 行 7: =../examples/p2_LOD3_00_School_main_op.py: 没有那个文件或目录
./LOD3.sh: 行 8: =../examples/p2_LOD3_00_School_main_LOD3.py: 没有那个文件或目录
Predicting corners with corner detector CNN....
image count in test path :3
Corner prediction process in 33.333333333333336%
Corner prediction process in 66.66666666666667%
Corner prediction process in 100.0%
Saving corner prediction process in 33.333333333333336%
Saving corner prediction process in 66.66666666666667%
Saving corner prediction process in 100.0%
Morphological operations in masks 33.333333333333336%
Morphological operations in masks 66.66666666666667%
Morphological operations in masks 100.0%
labeling and regionprops. Saving final corners process in 33.333333333333336%
labeling and regionprops. Saving final corners process in 66.66666666666667%
labeling and regionprops. Saving final corners process in 100.0%
Predicting openings with semantic segmentation...
Saving opening prediction process in 33.333333333333336%
Saving opening prediction process in 66.66666666666667%
Saving opening prediction process in 100.0%
Morphological operations in masks 33.333333333333336%
Morphological operations in masks 66.66666666666667%
Morphological operations in masks 100.0%
./LOD3.sh: 行 10:  6216 已杀死               PYTHONPATH=${LOD3PATH} PATH=$PATH:${FREECADPATH} python $main_op_file $@
FreeCAD 0.19, Libs: 0.19R21775 (Git)
(c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2020
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Exception while processing file: ../examples/p2_LOD3_00_School_main_op.py [No module named 'PIL']
Building LOD3
Recompute......
Found a shape containing curves, triangulating
Successfully written ../results/p2_LOD3_00_School/LOD3.obj

**Comment by bgpantojar** [comment]
Hello,

Indeed the error should not affect the result. There is a model SSD that was used at the beginning of the project but not for the version published with the paper. That model makes to rise the warning but it is normal.

Best,
Bryan

**Comment by yebuxiu123** [comment]
Thank you very much for your answer. I would like to ask again how can I visualize the final lod3 model with building surface information as in your paper

**Comment by bgpantojar** [comment]
Which information exactly?

**Comment by yebuxiu123** [comment]
Thank you for your attention to my question, but you seem to have misunderstood my meaning. What I want to know is how do I visualize the lod3 model generated after running the sample code  
./LOD3.sh ../examples/p2_LOD3_00_School_main_op.py ../examples/p2_LOD3_00_School_main_LOD3.py

**Comment by bgpantojar** [comment]
After running the codes, it should be generated a filed called LOD3.obj.. I usually visualize it using meshlab or open3d for example. Do you get that file? If not, there should be some error

**Comment by yebuxiu123** [comment]
Thank you very much for your answer. I generated this file LOD3.obj. But when I opened it using meshlab, I got the error in the picture below, and only one side of the visualized building model has a window. There are no Windows on any other side. Is this normal？
![054faab1ec0372afc4ded668c9c731d](https://user-images.githubusercontent.com/74604115/230870644-05f176b3-c5ed-4ebd-bb9b-e46500d3c4bf.png)
![211c334d65117817f00c46c724b6a68](https://user-images.githubusercontent.com/74604115/230870671-6425f716-0831-402c-bf92-fc86ce9ed560.png)

**Comment by bgpantojar** [comment]
That is just a warning about material properties. It is not important. There should be also a openings.obj file created... Check there if there are all the openings (that building if I recall properly has 3 facades with openings and one without). If you would like, share with me your output files "LOD3.obj" and "openings.obj". I can give a look at it
