### ISSUE TITLE
Annotation Tool for creating dataset 

### ISSUE THREAD

**Issue by rucha97** [bgpantojar/LOD3_buildings#2]
Hi, 
Thank you for the great work you have put up.

I want to create my own dataset of different types of buildings and train the network so I was wondering which annotation tool to use. Can you please tell me which tool was used while creating the dataset for labeling the opening corners, openings, and facade of the masonry buildings?

**Comment by bgpantojar** [comment]
Hello,

The labeling can be made using: https://github.com/abreheret/PixelAnnotationTool

The model's architecture for training can be found in: https://github.com/ternaus/TernausNet 

Best,
Bryan

**Comment by rucha97** [comment]
Thank you very much for your response.

I would appreciate it if you could give steps to prepare the dataset.

I want to know which labels did you use and what steps did you take to prepare ground truth images of the facade, openings, and opening corners.

Best regards,
Rucha

**Comment by bgpantojar** [comment]
The input image and labels for training look like these:

![IMG_2315](https://user-images.githubusercontent.com/35929939/232603136-fc0529e9-5fb2-4de7-abf1-7491722d0bcf.JPG)
![IMG_2315_mask_c](https://user-images.githubusercontent.com/35929939/232603147-2c9da050-cb7e-41e1-9f53-24a5ee0180e0.png)
![IMG_2315_mask_f](https://user-images.githubusercontent.com/35929939/232603150-fa905463-1d66-4016-9f63-a012abefa607.png)
![IMG_2315_mask_o](https://user-images.githubusercontent.com/35929939/232603152-2b111276-6198-488f-bd5c-19e51ea2b233.png)

To generate the labels for the facade and windows I actually use this tool:
https://www.robots.ox.ac.uk/~vgg/software/via/
And then I wrote an script to generate the previously shown binary images. You can also use the https://github.com/abreheret/PixelAnnotationTool to annotate everything.

BEst,
Bryuan

**Comment by rucha97** [comment]
Okay, thank you very much. I will try these tools and get back to you if for any queries.
