### ISSUE TITLE
[problem] Exception while processing file: ../examples/1lod.py [invalid literal for int() with base 10: 'anchor']

### ISSUE THREAD

**Issue by Panjh0218** [bgpantojar/LOD3_buildings#3]
Hello author, I am very interested in your project. But I encountered some problems while reproducing. When I created my own digital twin LOD3 model as required, the following error occurred. If you could help me answer, I would greatly appreciate it.

    Exception while processing file: ../examples/1lod.py [invalid literal for int() with base 10: 'anchor']

The entire error reporting process is as follows：

     ./LOD3.sh ../examples/1op.py ../examples/1lod.py
    ./LOD3.sh: 行 7: =../examples/1op.py: 没有那个文件或目录
    ./LOD3.sh: 行 8: =../examples/1lod.py: 没有那个文件或目录
    Traceback (most recent call last):
      File "/home/zjh/anaconda3/envs/lod3/lib/python3.7/site-packages/torch/__init__.py", line 172, in _load_global_deps
        ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
      File "/home/zjh/anaconda3/envs/lod3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /home/zjh/anaconda3/envs/lod3/lib/python3.7/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol 
    cublasLtGetStatusString, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "../examples/1op.py", line 11, in <module>
        from opening_detector import main_op_detector
      File "/home/LOD3_buildings-master/lod3_buildings/src/opening_detector.py", line 21, in <module>
        import torch
      File "/home/zjh/anaconda3/envs/lod3/lib/python3.7/site-packages/torch/__init__.py", line 217, in <module>
        _load_global_deps()
      File "/home/zjh/anaconda3/envs/lod3/lib/python3.7/site-packages/torch/__init__.py", line 178, in _load_global_deps
        _preload_cuda_deps()
     File "/home/zjh/anaconda3/envs/lod3/lib/python3.7/site-packages/torch/__init__.py", line 158, in _preload_cuda_deps
        ctypes.CDLL(cublas_path)
      File "/home/zjh/anaconda3/envs/lod3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /home/zjh/anaconda3/envs/lod3/lib/python3.7/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol 
    cublasLtGetStatusString, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
    FreeCAD 0.19, Libs: 0.19R21775 (Git)
    (c) Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2020
    FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
    FreeCAD wouldn't be possible without FreeCAD community.
      #####                 ####  ###   ####  
      #                    #      # #   #   # 
      #     ##  #### ####  #     #   #  #   # 
      ####  # # #  # #  #  #     #####  #   # 
      #     #   #### ####  #    #     # #   # 
      #     #   #    #     #    #     # #   #  ##  ##  ##
      #     #   #### ####   ### #     # ####   ##  ##  ##

    Exception while processing file: ../examples/1op.py [No module named 'PIL']
    Building LOD3
    Exception while processing file: ../examples/1lod.py [invalid literal for int() with base 10: 'anchor']

Best regards,
PJH

**Comment by bgpantojar** [comment]
Hello,

Thanks for the interest.

I haven't experienced that. If the translation of the Chinese characters is right, the input files are placed wrongly as they are not found (although I assumed you placed them in the proper folder).

If you like to share the input data I could give a look in my machine. Otherwise take into account I tested the codes with Ubuntu 18.04 lts, and, the building typology must be similar to the ones from the paper (otherwise you might need to train models to segment the openings and facade).

Best,
Bryan

**Comment by Panjh0218** [comment]
Thank you for your answer.

The reason for my error may be due to the difference between the input building type and the one in the paper. I will try to solve it.

Best,
PJH
