### ISSUE TITLE
Error while generating LOD3 using dense polyfit object

### ISSUE THREAD

**Issue by rucha97** [bgpantojar/LOD3_buildings#4]
Hello Dr. Bryan,

I encountered an error while generating LOD3 using a dense polyfit object as below:

  _File "../src\opening_builder.py", line 90, in build_face
    face = Part.Face(poly)
Part.OCCError: Failed to create face from wire_

Do you have any idea about what could be the issue? 

Also, how do I save a point cloud/mesh from Meshroom?
For generating LOD2 models so far, I have been using mesh created by Agisoft Metashape (licensed). 

Best regards,
Rucha

**Comment by bgpantojar** [comment]
Hello,

It seems that the openings were not properly created.

For the point cloud you need to create an extra node to convert the sfm format and connect it to the sfm node or to the mesh node (activating in this node the save option of the dense point cloud).

Best,
Bryan
